INSERT INTO building (building_name) values ('výroba');
INSERT INTO building (building_name) values ('úèetnictví');
INSERT INTO building (building_name) values ('headquarters');
INSERT INTO building (building_name) values ('závodní jídelna');
INSERT INTO building (building_name) values ('odpadová hala');
INSERT INTO building (building_name) values ('strojírenství');

INSERT INTO manager (manager_firstname,manager_surname,salary,building_id) values ('Miroslav','Hladký',100000.00,1);
INSERT INTO manager (manager_firstname,manager_surname,salary,building_id) values ('Natálie','Syrová',82000,2);
INSERT INTO manager (manager_firstname,manager_surname,salary,building_id) values ('Rudolf','Bednaøík',135000,3);
INSERT INTO manager (manager_firstname,manager_surname,salary,building_id) values ('Alžbìta','Stupková',35000,4);
INSERT INTO manager (manager_firstname,manager_surname,salary,building_id) values ('Marcel','Šimèík',43200,5);

INSERT INTO job (job_type,salary) values ('dìlník',22000.00);
INSERT INTO job (job_type,salary) values ('uklízeèka',18000.00);
INSERT INTO job (job_type,salary) values ('vedoucí výroby',33200.00);
INSERT INTO job (job_type,salary) values ('IT technik',35000.00);
INSERT INTO job (job_type,salary) values ('úèetní',29500.00);
INSERT INTO job (job_type,salary) values ('kuchaø',22000.00);
INSERT INTO job (job_type,salary) values ('správce odpadù',27500.00);
INSERT INTO job (job_type,salary) values ('pomocný kuchaø',20000.00);
INSERT INTO job (job_type,salary) values ('strojaø',51000.00);

INSERT INTO customer(customer_f_name,customer_s_name) values ('Dominik','Strouhal');
INSERT INTO customer(customer_f_name,customer_s_name) values ('Kateøina','Karelová');
INSERT INTO customer(customer_f_name,customer_s_name) values ('Martin','Koøínek');
INSERT INTO customer(customer_f_name,customer_s_name) values ('Natálie','Pavelková');
INSERT INTO customer(customer_f_name,customer_s_name) values ('Michaela','Jahodová');

INSERT INTO car(car_brand,car_color,customer_id) values ('Volkswagen','èervená',3);
INSERT INTO car(car_brand,car_color,customer_id) values ('Volkswagen','èerná',2);
INSERT INTO car(car_brand,car_color,customer_id) values ('BMW','èerná',4);
INSERT INTO car(car_brand,car_color,customer_id) values ('BMW','bílá',1);
INSERT INTO car(car_brand,car_color,customer_id) values ('Škoda','støíbrná',5);

INSERT INTO contact(email,phone_number,customer_id) values ('domca.str@seznam.cz','+420621345876',1);
INSERT INTO contact(email,phone_number,customer_id) values ('katka.karelova@gmail,pswd.com','+420720753682',2);
INSERT INTO contact(email,phone_number,customer_id) values ('koren@centrum.cz','+420608879998',3);
INSERT INTO contact(email,phone_number,customer_id) values ('natalie.pavelkova@gmail,pswd.com','+420555666777',4);
INSERT INTO contact(email,phone_number,customer_id) values ('miluju,auta@seznam.cz','+420725438876',5);

INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Alena','Samková','alena.samkova@automotive.cz','BgZNZ@Vn7D',2);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Petr','Kalivoda','petr.kal@automotive.cz','P@npUd809L',3);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Hana','Jandová','alena.jand@automotive.cz','tqA*1LIZfj',4);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Alois','Smola','alois.smola@automotive.cz','Xy$y^mWXVn',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Luboš','Veverka','lubos.vever@automotive.cz','^#BMoZKb5F',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Markéta','Janková','mj.1@automotive.cz','G@VjSFS&P7',5);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Jakub','Ferenc','jakub.ferenc@automotive.cz','53dI$eNipl',5);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Zbynìk','Hrnèíø','zbynek.hrncir@automotive.cz','3IdrL9aJ@x',2);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Vojtìch','Sluka','vojtech.sluk@automotive.cz','=A3ResP4qa',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Štìpán','Beèvár','stepan.becvar@automotive.cz','8*Lxothlz8',4);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Šimon','Motl','simon.motl@automotive.cz','SP$t?ln2T2',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Rostislav','Kropáèek','rost.krop@automotive.cz','7rETh*9o#u',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Richard','Maršík','richard.mars@automotive.cz','fuRO49o#AH',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Adam','Vybíral','nevybral@automotive.cz','3Ebr$cIM1b',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Bohuslav','Berky','bohus.berky@automotive.cz','tHe$6Wr&va',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Jan','Hromádka','jan.hromadka@automotive.cz','2l*u?OMAdI',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Martin','Provazník','martin.provaz@automotive.cz','dR4swetrl*',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Vítìzslav','Èerný','vita.cerny@automotive.cz','*r6kOdrLyE',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Miloš','Vrzal','vrzvrz@automotive.cz','nU*p1viPra',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Petr','Trèka','petr.trcka@automotive.cz','7iD=woChav',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Dalibor','Válek','dalibor.valek@automotive.cz','$1kIWro8He',5);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Barbora','Ptáèková','bara.ptack@automotive.cz','xl-HuPhA#2',2);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Jiøí','Vašák','jiri.vasak@automotive.cz','m2Th&n8XEr',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Jitka','Peterková','jitka.peter@automotive.cz','1It=#PrAji',4);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Ludìk','Dìdek','ludek.dedek@automotive.cz','s#3ke@ogEk',3);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Natálie','Danielová','natalie.dan@automotive.cz','pUD!R77L?o',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Božena','Fuksová','bozena.fuks@automotive.cz','s4A&=tIFId',5);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Michal','Starý','michal.stary@automotive.cz','&a4OcH_tad',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Rostislav','Šebek','rosta.sebek@automotive.cz','gIy0TucoK$',5);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Tomáš','Adam','tomas.adam@automotive.cz','pasT8?lzu+',3);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Jana','Èížková','jana.cizk@automotive.cz','qaHlq$Mi5P',5);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Soòa','Bauerová','sona.bauer@automotive.cz','3@MupR&w3C',3);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Šimon','Sokol','simon.sokol@automotive.cz','sI*l+hiD5o',3);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Helena','Slezáková','helena.slezak@automotive.cz','wlmA9ra3@m',4);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Tomáš','Bartošek','tomas.bartos@automotive.cz','s&aP6!hEml',3);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('František','Benda','fanos.benda@automotive.cz','?osT7trEpa',3);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Emilie','Kubátová','emilie.kubat@automotive.cz','Pro8-TaZ8s',2);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Markéta','Dvorská','maka.dvorska@automotive.cz','7h3JurOf-U',5);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Radim','Doležal','radim.dolez@automotive.cz','w*prE_O0RU',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Vendula','Pechová','vendy.pech@automotive.cz','w?uqadlr4S',3);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Lubomír','Vaníèek','lubomir.van@automotive.cz','ph1+R&drOX',6);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Filip','Myška','filip.myska@automotive.cz','f1IdRA+ine',6);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Lubomír','Beneš','lubomir.benes@automotive.cz','Y_hu&iR5Me',6);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Ludvík','Daniš','ludva.danis@automotive.cz','xa*I=8stlh',6);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Ján','Kudrna','jan.kudrna@automotive.cz','b+u3e1T*jA',6);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Matìj','Dvoøáèek','matej.dvor@automotive.cz','9$zEYuBOxe',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Tomáš','Hlaváè','tom.hlavac@automotive.cz','3h&viCho@o',1);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Ludvík','Gajdoš','ludva.gajdos@automotive.cz','C@U2ug9pUt',5);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Zbynìk','Trnak','zbynek.trnka@tomotive.cz','4*CoNlSwiT',5);
INSERT INTO employee (first_name,surname,mail,pswd,building_id) values ('Kamil','Koutný','kamil.koutny@automotive.cz','4*CoNlSwiT',5);

INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',1,5);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',2,5);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',3,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',4,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',5,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',6,7);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',7,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',8,5);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',9,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',10,6);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,11,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2025-01-01',12,3);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,13,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,14,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,15,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,16,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,17,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,18,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,19,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,20,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,21,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2024-01-01',22,5);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,23,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,24,8);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2024-01-01',25,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,26,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,27,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2025-01-01',28,3);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,29,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,30,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,31,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,32,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',33,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,34,6);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',35,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',36,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,37,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,38,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,39,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,40,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,41,9);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,42,9);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',43,9);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,44,9);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',45,9);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,46,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,47,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,48,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,49,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,50,7);

INSERT INTO address (city,street,street_number,zip_code) values ('Nechanice','Na Kopeèku', 1544, 50315);
INSERT INTO address (city,street,street_number,zip_code) values ('Louny','Louny',17123,44001);
INSERT INTO address (city,street,street_number,zip_code) values ('Úhretice','Jiráskova',1045,53832);
INSERT INTO address (city,street,street_number,zip_code) values ('Zajecov','K Lukárnì',5188,26736);
INSERT INTO address (city,street,street_number,zip_code) values ('Rožmitál pod Tremšínem', 'U medvídkù',2155,26242);


INSERT INTO car_has_workers (car_id,employee_id,deadline) values(1,12,'2022-10-05');
INSERT INTO car_has_workers (car_id,employee_id,deadline) values(1,14,'2022-10-7');
INSERT INTO car_has_workers (car_id,employee_id,deadline) values(1,44,'2022-10-12');
INSERT INTO car_has_workers (car_id,employee_id,deadline) values(3,1,'2022-4-22');
INSERT INTO car_has_workers (car_id,employee_id,deadline) values(3,15,'2022-4-27');

INSERT INTO car_in_building (car_id,building_id,parts) values(1,1,'Volant');
INSERT INTO car_in_building (car_id,building_id,parts) values(1,6,'Motor');
INSERT INTO car_in_building (car_id,building_id,parts) values(2,1,'Zrcátka');
INSERT INTO car_in_building (car_id,building_id,parts) values(2,6,'Motor');
INSERT INTO car_in_building (car_id,building_id,parts) values(4,1,'Sedadla');
INSERT INTO car_in_building (car_id,building_id,parts) values(4,6,'Motor');

INSERT INTO employee_has_address (address_id, employee_id, address_type) values (1,1,'Korespondenèní adresa');
INSERT INTO employee_has_address (address_id, employee_id, address_type) values (3,1,'Adresa trvalého bydlištì');
INSERT INTO employee_has_address (address_id, employee_id, address_type) values (4,2,'Korespondenèní adresa');
INSERT INTO employee_has_address (address_id, employee_id, address_type) values (2,3,'Korespondenèní adresa');
INSERT INTO employee_has_address (address_id, employee_id, address_type) values (5,3,'Adresa trvalého bydlištì');

INSERT INTO manager_has_address (manager_id, address_id, address_type) values (1,1,'Adresa trvalého bydlištì');
INSERT INTO manager_has_address (manager_id, address_id, address_type) values (5,1,'Adresa trvalého bydlištì');    
INSERT INTO manager_has_address (manager_id, address_id, address_type) values (4,4,'Korespondenèní adresa');    
INSERT INTO manager_has_address (manager_id, address_id, address_type) values (2,3,'Korespondenèní adresa');    
INSERT INTO manager_has_address (manager_id, address_id, address_type) values (3,5,'Adresa trvalého bydlištì');    