                                INSERT INTO building (building_name) values ('výroba');
INSERT INTO building (building_name) values ('úèetnictví');
INSERT INTO building (building_name) values ('headquarters');
INSERT INTO building (building_name) values ('závodní jídelna');
INSERT INTO building (building_name) values ('odpadová hala');
INSERT INTO building (building_name) values ('strojírenství');

INSERT INTO manager (manager_firstname,manager_surname,salary,building_id) values ('Miroslav','Hladký',100000.00,1);
INSERT INTO manager (manager_firstname,manager_surname,salary,building_id) values ('Natálie','Syrová',82000,2);
INSERT INTO manager (manager_firstname,manager_surname,salary,building_id) values ('Rudolf','Bednaøík',135000,3);
INSERT INTO manager (manager_firstname,manager_surname,salary,building_id) values ('Alžbìta','Stupková',35000,4);
INSERT INTO manager (manager_firstname,manager_surname,salary,building_id) values ('Marcel','Šimèík',43200,5);

INSERT INTO job (job_type,salary) values ('dìlník',22000.00);
INSERT INTO job (job_type,salary) values ('uklízeèka',18000.00);
INSERT INTO job (job_type,salary) values ('vedoucí výroby',33200.00);
INSERT INTO job (job_type,salary) values ('IT technik',35000.00);
INSERT INTO job (job_type,salary) values ('úèetní',29500.00);
INSERT INTO job (job_type,salary) values ('kuchaø',22000.00);
INSERT INTO job (job_type,salary) values ('správce odpadù',27500.00);
INSERT INTO job (job_type,salary) values ('pomocný kuchaø',20000.00);
INSERT INTO job (job_type,salary) values ('strojaø',51000.00);

INSERT INTO car(car_brand,car_color,customer_id) values ('Volkswagen','èervená',NULL);
INSERT INTO car(car_brand,car_color,customer_id) values ('Volkswagen','èerná',NULL);
INSERT INTO car(car_brand,car_color,customer_id) values ('BMW','èerná',NULL);
INSERT INTO car(car_brand,car_color,customer_id) values ('BMW','bílá',NULL);
INSERT INTO car(car_brand,car_color,customer_id) values ('Škoda','støíbrná',NULL);

INSERT INTO customer(customer_f_name,customer_s_name,car_id) values ('Dominik','Strouhal',1);
INSERT INTO customer(customer_f_name,customer_s_name,car_id) values ('Kateøina','Karelová',2);
INSERT INTO customer(customer_f_name,customer_s_name,car_id) values ('Martin','Koøínek',3);
INSERT INTO customer(customer_f_name,customer_s_name,car_id) values ('Natálie','Pavelková',4);
INSERT INTO customer(customer_f_name,customer_s_name,car_id) values ('Michaela','Jahodová',5);

INSERT INTO employee (first_name,surname,mail,building_id) values ('Alena','Samková','alena.samkova@automotive.cz',2);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Petr','Kalivoda','petr.kal@automotive.cz',3);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Hana','Jandová','alena.jand@automotive.cz',4);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Alois','Smola','alois.smola@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Luboš','Veverka','lubos.vever@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Markéta','Janková','mj.1@automotive.cz',5);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Jakub','Ferenc','jakub.ferenc@automotive.cz',5);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Zbynìk','Hrnèíø','zbynek.hrncir@automotive.cz',2);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Vojtìch','Sluka','vojtech.sluk@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Štìpán','Beèvár','stepan.becvar@automotive.cz',4);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Šimon','Motl','simon.motl@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Rostislav','Kropáèek','rost.krop@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Richard','Maršík','richard.mars@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Adam','Vybíral','nevybral@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Bohuslav','Berky','bohus.berky@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Jan','Hromádka','jan.hromadka@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Martin','Provazník','martin.provaz@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Vítìzslav','Èerný','vita.cerny@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Miloš','Vrzal','vrzvrz@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Petr','Trèka','petr.trcka@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Dalibor','Válek','dalibor.valek@automotive.cz',5);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Barbora','Ptáèková','bara.ptack@automotive.cz',2);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Jiøí','Vašák','jiri.vasak@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Jitka','Peterková','jitka.peter@automotive.cz',4);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Ludìk','Dìdek','ludek.dedek@automotive.cz',3);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Natálie','Danielová','natalie.dan@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Božena','Fuksová','bozena.fuks@automotive.cz',5);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Michal','Starý','michal.stary@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Rostislav','Šebek','rosta.sebek@automotive.cz',5);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Tomáš','Adam','tomas.adam@automotive.cz',3);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Jana','Èížková','jana.cizk@automotive.cz',5);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Soòa','Bauerová','sona.bauer@automotive.cz',3);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Šimon','Sokol','simon.sokol@automotive.cz',3);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Helena','Slezáková','helena.slezak@automotive.cz',4);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Tomáš','Bartošek','tomas.bartos@automotive.cz',3);
INSERT INTO employee (first_name,surname,mail,building_id) values ('František','Benda','fanos.benda@automotive.cz',3);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Emilie','Kubátová','emilie.kubat@automotive.cz',2);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Markéta','Dvorská','maka.dvorska@automotive.cz',5);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Radim','Doležal','radim.dolez@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Vendula','Pechová','vendy.pech@automotive.cz',3);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Lubomír','Vaníèek','lubomir.van@automotive.cz',6);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Filip','Myška','filip.myska@automotive.cz',6);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Lubomír','Beneš','lubomir.benes@automotive.cz',6);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Ludvík','Daniš','ludva.danis@automotive.cz',6);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Ján','Kudrna','jan.kudrna@automotive.cz',6);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Matìj','Dvoøáèek','matej.dvor@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Tomáš','Hlaváè','tom.hlavac@automotive.cz',1);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Ludvík','Gajdoš','ludva.gajdos@automotive.cz',5);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Zbynìk','Trnak','zbynek.trnka@tomotive.cz',5);
INSERT INTO employee (first_name,surname,mail,building_id) values ('Kamil','Koutný','kamil.koutny@automotive.cz',5);

INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',1,5);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',2,5);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',3,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',4,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',5,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',6,7);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',7,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',8,5);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',9,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',10,6);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,11,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2025-01-01',12,3);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,13,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,14,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,15,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,16,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,17,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,18,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,19,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,20,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,21,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2024-01-01',22,5);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,23,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,24,8);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2024-01-01',25,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,26,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,27,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2025-01-01',28,3);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,29,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,30,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,31,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,32,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',33,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,34,6);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',35,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',36,4);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,37,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,38,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,39,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,40,2);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,41,9);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,42,9);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',43,9);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,44,9);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values ('2023-01-01',45,9);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,46,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,47,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,48,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,49,1);
INSERT INTO employee_has_contract (contract_expiration,employee_id,job_id) values (NULL,50,7);